
plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Include:
    - "spec/**/*"
  Exclude:
    - "lib/**/*"
    - "bin/**/*"
    - "db/schema.rb"
    - "vendor/**/*"

Metrics/BlockLength:
  AllowedMethods:
    - context
    - describe
    - it
    - shared_examples
    - shared_examples_for
    - namespace
    - draw
    - configure
    - group

Style/Documentation:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/MultipleExpectations:
  Max: 3

RSpec/NamedSubject:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

Lint/EmptyBlock:
  Exclude:
    - "spec/factories/**/*"

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Rails/ReflectionClassName:
  Enabled: false

RSpec/VariableName:
  AllowedPatterns:
    - Authorization

RSpec/EmptyExampleGroup:
  Exclude:
    - "spec/requests/**/*"

Rails/Date:
  EnforcedStyle: flexible
