/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*', './app/views/layouts/*', './app/javascript/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    extend: {
      lineClamp: {
        7: '7',
        8: '8',
        16: '16',
      },
      colors: {
        black: 'rgb(var(--v-theme-black))',
        background: 'rgb(var(--v-theme-background))',
        surface: 'rgb(var(--v-theme-surface))',
        primary: 'rgb(var(--v-theme-primary))',
        'primary-hover': 'rgb(var(--v-theme-primaryHover))',
        'primary-active': 'rgb(var(--v-theme-primaryActive))',
        'tooltip-background': 'rgb(var(--v-theme-tooltipBackground))',
        'tooltip-text': 'rgb(var(--v-theme-tooltipText))',
        'workshop-blue': 'rgb(var(--v-theme-workshopBlue))',
        accent: 'rgb(var(--v-theme-accent))',
        secondary: 'rgb(var(--v-theme-secondary))',
        success: 'rgb(var(--v-theme-success))',
        info: 'rgb(var(--v-theme-info))',
        warning: 'rgb(var(--v-theme-warning))',
        grey: 'rgb(var(--v-theme-grey))',
        error: 'rgb(var(--v-theme-error))',
        neutral: 'rgb(var(--v-theme-neutral))',
        'training-orange': 'rgb(var(--v-theme-trainingOrange))',
        'training-orange-soft': 'rgb(var(--v-theme-trainingOrangeSoft))',
        'interview-blue-soft': 'rgb(var(--v-theme-interviewBlueSoft))',
        'fake-black': 'rgb(var(--v-theme-fakeBlack))',
        'dark-grey': 'rgb(var(--v-theme-darkGrey))',
        'middle-grey': 'rgb(var(--v-theme-middleGrey))',
        'light-grey': 'rgb(var(--v-theme-lightGrey))',
        'very-light-grey': 'rgb(var(--v-theme-veryLightGrey))',
        'positive-green': 'rgb(var(--v-theme-positiveGreen))',
        'positive-green-darken': 'rgb(var(--v-theme-positiveGreenDarken))',
        'lime-green': 'rgb(var(--v-theme-limeGreen))',
        'medium-orange': 'rgb(var(--v-theme-mediumOrange))',
        'negative-red': 'rgb(var(--v-theme-negativeRed))',
        'negative-red-lighten': 'rgb(var(--v-theme-darkmoodGlobalBg))',
        'transparent-positive-green': 'rgb(var(--v-theme-transparentPositiveGreen))',
        'transparent-medium-orange': 'rgb(var(--v-theme-transparentMediumOrange))',
        'transparent-negative-red': 'rgb(var(--v-theme-transparentNegativeRed))',
        'medium-orange-opacity': 'rgb(var(--v-theme-mediumOrangeOpacity))',
        'negative-red-opacity': 'rgb(var(--v-theme-negativeRedOpacity))',
        'positive-green-opacity': 'rgb(var(--v-theme-positiveGreenOpacity))',
        lighten2: '#70ABEF',
        'lighten4-custom': '#F4FAFF',
      },
      boxShadow: {
        medium: '0 2px 4px 0 rgba(0, 0, 0, 0.25)',
        'light-grey': '0px 2px 6px 0px rgba(16, 24, 40, 0.20)',
      },
    },
  },
  plugins: [require("@headlessui/tailwindcss")],
};
