development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://redis:6379/1" } %>
  channel_prefix: multi_magic_co_dev

test:
  adapter: test

staging:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://redis:6379/1" } %>
  channel_prefix: multi_magic_co_staging

production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: your_app_production
  ssl_params:
    verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %> # Only in development/testing; remove this in production
